import { executeToolCall } from '@mnem/tools'
import type { ToolCallInput } from '@mnem/tools'
import { loadVaultFrom } from '../vault-loader.js'

export interface ToolOptions {
  readonly startDir: string
  /** Dashed tool name as exposed by Claude Skill scripts, e.g. `read-note`. */
  readonly toolName: string
  /** JSON-encoded arguments. If omitted, defaults to `{}`. */
  readonly jsonArgs?: string
}

/**
 * Execute a single tool call from the command line. Used by the Claude Skill
 * scripts generated by `toClaudeSkill`.
 */
export async function runTool(options: ToolOptions): Promise<string> {
  const { vault } = await loadVaultFrom(options.startDir)
  try {
    const operation = options.toolName.replace(/-/g, '_')
    const args: Record<string, unknown> =
      options.jsonArgs === undefined || options.jsonArgs.length === 0
        ? {}
        : (JSON.parse(options.jsonArgs) as Record<string, unknown>)
    const call: ToolCallInput = { name: operation, arguments: args }
    const result = await executeToolCall(vault, call)
    return result.content
  } finally {
    await vault.close()
  }
}
